# Generated by Django 3.0.7 on 2020-07-01 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sleep.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('sleep_at', models.TimeField(default='12:00:00')),
                ('hours', models.FloatField(default=-1)),
                ('satisfaction_score', models.PositiveIntegerField(default=6, validators=[sleep.models.SleepRecord.validate_max])),
                ('tiredness', models.PositiveIntegerField(default=6, validators=[sleep.models.SleepRecord.validate_max])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
