# Generated by Django 3.0.7 on 2020-06-29 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0003_auto_20200629_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleeprecord',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
